baseURL = "/"

languageCode = "en-us"
title = "Technical Blog"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en-us"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
disqusShortname = "rackspace-docs"
paginate = 7
canonifyurls = true
metaDataFormat = "yaml"

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[permalinks]
  posts = "/:year/:month/:slug/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true

[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]

[params]
    ordersectionsby = "weight" # ordersectionsby = "title"
    disableSearch = false # default is false
    disableReadmoreNav = false # set true to hide prev/next navigation, default is false
    highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
    menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
    custom_css = [
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10
    hierarchicalCategories = true
    syntaxHighlighter = "highlight.js"
    clearReading = true
    # swapPaginator = true
    dateformat = "January 2, 2006"
    description = "Content management system for sites built with static site generators. Get the speed, security, and reliability of static and the power of a Headless CMS."
    ghrepo = "https://github.com/rackerlabs/technical-blog"
    ghrepo_edit = "https://github.com/rackerlabs/technical-blog/edit/develop/hugo/content/"
    ghrepo_new = "https://github.com/rackerlabs/technical-blog/issues/new"
    [params.algolia]
        params = ["blogs", "posts", "authors"]
        vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
[menu]
  [[menu.main]]
      identifier = "developer_home"
      name = "Developer Home"
      url = "https://developer.rackspace.com/"
      weight = 1
  [[menu.main]]
      identifier = "developer_documentation"
      name = "Developer Documentation"
      url = "https://developer.rackspace.com/docs/"
      weight = 2
  [[menu.main]]
      identifier = "blogs"
      name = "Blogs"
      url = "/#"
      weight = 3
      [[menu.main]]
          identifier = "technical_blog"
          name = "Technical Blog"
          url = "/blog"
          weight = 1
          parent = "blogs"
      [[menu.main]]
          identifier = "rackspace_blog"
          name = "Rackspace Blog"
          url = "https://www.rackspace.com/blog"
          weight = 2
          parent = "blogs"
      [[menu.main]]
          identifier = "rackspace_solve"
          name = "Solve: thought "
          url = "https://www.rackspace.com/solve"
          weight = 3
          parent = "blogs"
  [[menu.main]]
      identifier = "support_documentation"
      name = "Support Documentation"
      url = "https://support.rackspace.com/"
      weight = 4

