baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Technical Blog"
theme = "rackspace-docs"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    ordersectionsby = "weight" # ordersectionsby = "title"
    disableSearch = false # default is false
    disableReadmoreNav = false # set true to hide prev/next navigation, default is false
    highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
    menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
    custom_css = [
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10

[menu]
  [[menu.main]]
      identifier = "developer_home"
      name = "Developer Home"
      url = "https://developer.rackspace.com/"
      weight = 1
  [[menu.main]]
      identifier = "developer_documentation"
      name = "Developer Documentation"
      url = "https://developer.rackspace.com/docs/"
      weight = 2
  [[menu.main]]
      identifier = "blogs"
      name = "Blogs"
      url = "/#"
      weight = 3
      [[menu.main]]
          identifier = "technical_blog"
          name = "Technical Blog"
          url = "/blog"
          weight = 1
          parent = "blogs"
      [[menu.main]]
          identifier = "rackspace_blog"
          name = "Rackspace Blog"
          url = "https://www.rackspace.com/blog"
          weight = 2
          parent = "blogs"
      [[menu.main]]
          identifier = "rackspace_solve"
          name = "Solve: thought "
          url = "https://www.rackspace.com/solve"
          weight = 3
          parent = "blogs"
  [[menu.main]]
      identifier = "support_documentation"
      name = "Support Documentation"
      url = "https://support.rackspace.com/"
      weight = 4


[outputs]
home = [ "HTML", "RSS", "JSON"]
