[build.environment]
  YARN_VERSION = "1.22.4"
  NPM_VERSION = "6.14.5"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[plugins]]
  package = "netlify-plugin-algolia-index"

[[redirects]]
  from = "/docs"
  to = "https://developer.rackspace.com/docs/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}